version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 3000:3000
            - 9229:9229
        depends_on:
            - mongodb
        links:
            - mongodb
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    mongodb:
      image: mongo
      container_name: nesjs_mongo_dev
      volumes:
        - data-mongodb:/data/db
      ports:
        - "27018:27017"
      networks:
        - nesjs-network

networks:
    nesjs-network:

volumes:
  data-mongodb:
    driver: local
    
